### ISSUE TITLE
Dupe issue

### ISSUE THREAD

**Issue by Artuto** [serversigns/ServerSigns#37] opened 2020-07-03 17:52 UTC
We have had a player use a sign that had a item price to dupe the execution of the commands without removing the item.

I do not feel like publishing how it is done, how can I contact you?

**Comment by EpiCanard** [comment] 2020-07-04 14:28
You can contact me on [spigot](https://www.spigotmc.org/conversations/add?to=EpiCanard) or by mail to epicanard@gmail.com

**Comment by Artuto** [comment] 2020-07-04 15:03
I've sent you a DM on Spigot

**Comment by EpiCanard** [comment] 2020-07-04 15:48
Oh ok I see, thank you for you report. I see more or less where is the bug.

Sorry, sadly I don't have much free time I will fix it when I will have the time. :/

Note for me: `InventoryUtils.scan`

**Comment by Artuto** [comment] 2020-07-04 16:00
If I can figure it out I'll throw you a PR

**Comment by EpiCanard** [comment] 2020-07-04 16:05
Thank you :)

**Comment by EpiCanard** [comment] 2020-10-03 20:11
Hello, 

@Artuto I tried to reproduce the bug with 1.16 version and I didn't succeed, everything works as expected.
Which version of minecraft and svs do you use ?

**Comment by EpiCanard** [comment] 2020-11-17 21:07
@Artuto It seems to be an error that happen only with paper 1.16. With paper 1.15 or spigot 1.15/1.16 it works as expected.

**Comment by EpiCanard** [comment] 2020-11-17 22:46
I tried with multiple versions : spigot 1.15 and 1.16, paper 1.15 and 1.16 and it always works as expected.

I close this issue, please reopen it if you still have the bug.

**Closed as completed by EpiCanard** 2020-11-17 22:46 UTC
Labels: :heavy_exclamation_mark: Bug
